apiVersion: v1
kind: ConfigMap
metadata:
  name: configs
  data: ./configs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: immushroom/hello
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        - containerPort: 8001
      - name: prometheus
        image: prom/prometheus
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: prom-config
          mountPath: /etc/prometheus/
        ports:
        - containerPort: 9090
      - name: grafana
        image: grafana/grafana-oss
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: grafana-config
          mountPath: /etc/grafana/provisioning/
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "MYPASSWORT"
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
      volumes:
      - name: prom-config
        hostPath:
          path: ./prom_config/
          type: DirectoryOrCreate
      - name: grafana-config
        hostPath:
          path: ./graf_config/provisioning/
          type: DirectoryOrCreate