apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-balancer
spec:
  ports:
  - port: {{ .Values.ports.hello_port }}
    name: webport
    targetPort: 8000
  - port: {{ .Values.ports.prom_port }}
    name: prom
    targetPort: 9090
  - port: {{ .Values.ports.grafana_port }}
    name: graf
    targetPort: 3000
  selector:
    app: hello
  type: LoadBalancer