{
 "title": "Hello-app",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Virtual memory, MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"hello-app\"} / 1024^2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU time, sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"hello-app\"}"
    }
   ]
  },
  { "title": "Web app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(server_latency_seconds_sum{job=\"hello-app\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "server_requests_total{job=\"hello-app\"}"
    }
   ]
  }
 ]
}